- src/debugger_requests.jl
Fixes a bug from bug reporting.
> Fix a bug in how we handle missing parameters

- src/debugger_requests.jl
This simply adds the current function's defining module as a scope.
> Global variables

- src/debugger_requests.jl
- src/debugger_utils.jl
> Handle error situation when trying to debug a non existent file

- src/debugger_requests.jl
With this PR user's terminal won't be spammed with the internal error, but instead she won't get any indication about why debugger doesn't do anything (just because we have not set up any UI for these cases).
It's obviously better to setup the UI, but I'm not sure we should setup that first, or merge this for now.
> handle a case when the expression lowering fails

- src/debugger_requests.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1843.
> fix condition for line breakpoints

- src/debugger_requests.jl
We really need to fix the `Module` shadowing here...
> Fix get_obj_by_accessor

- src/debugger_requests.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2314 and fixes https://github.com/julia-vscode/julia-vscode/issues/2231.
For every PR, please check the following:
> Handle errors in show/repr

- src/debugger_requests.jl
- src/protocol/responses.jl
- src/protocol/types.jl
> fix index type for SparseArrays

- src/debugger_requests.jl
- src/packagedef.jl
> Deemphasize kw-func wrappers

- src/debugger_requests.jl
by looking for them in pwd.
Fixes https://github.com/julia-vscode/julia-vscode/issues/2698.
> Allow relative program paths

- src/debugger_requests.jl
- src/debugger_utils.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2520.
> limit repr output

- Project.toml
- src/debugger_requests.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2774.
> Update to JuliaInterpreter 0.9

- src/debugger_core.jl
- src/debugger_requests.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2784.
> Improve display error handling

- src/debugger_utils.jl
Probably fixes https://github.com/julia-vscode/julia-vscode/issues/2844.
> Fix deepcopy issue

- src/debugger_utils.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2932.
> Remove copy shenanigans in calls_on_line

- src/debugger_requests.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2516#issuecomment-1211872074.
> Fix ALL_MODULES_EXCEPT_MAIN main exception

- src/debugger_requests.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2516#issuecomment-1212100848.
> Re-apply interpreted modules

- src/packagedef.jl
> Typo in packagedef.jl

- src/debugger_requests.jl
Fixes https://github.com/julia-vscode/DebugAdapter.jl/issues/59#issuecomment-2197888957
> fix: Allow missing juliaEnv

- src/debugger_requests.jl
- src/debugger_utils.jl
Fixes #82. And some more bugs.
> Fix bug with frame access from session

- src/DebugEngines.jl
- src/debugger_requests.jl
- src/packagedef.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/3651.
> Fix source handling

- src/debugger_requests.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/3657.
> Fix disconnect

- src/DAPRPC/core.jl
> Correctly send boolean success type

- README.md
- src/debugger_requests.jl
- src/packagedef.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/3673
> Fix terminate sequence

- Project.toml
- src/packagedef.jl
> Import UUIDs properly

- src/debugger_requests.jl
- src/packagedef.jl
> Extend varrefs lifetime to be spec compliant

- src/debugger_requests.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/3308
> Handle incorrect evaluate request gracefully

- src/DAPRPC/typed.jl
> Properly handle Union Nothing types
